### ISSUE TITLE
Hourly output is missing an hour

### ISSUE THREAD

**Issue by hobsonbw** [canmet-energy/btap_batch#88]
When running btap_batch, the hourly simulation outputs store in hourly.csv contain 8759 timesteps, and not the 8760 hours expected for a full yearly simulation. The timestamps appear to include the time change in the spring when the clocks move forward (e.g., 2006-04-02 2:00 is missing), but are missing the duplicate hour in the fall when the clocks go back (e.g., 2006-10-29 1:00 should be duplicated but is not). However, the timestamps should not be using daylight savings to begin with. 

- The last hourly outputs on-hand without this issue were produced on 2022-12-15. 
- The earliest hourly outputs on-hand with the issue were produced on 2023-07-11.

**Comment by phylroy** [comment]
For some reason, changing the image that was based on NREL's docker-openstudio with our os_sdk_container which also had a fix for ASCCII/UTF-8 encoding issues solved the problem.  Not sure why.. but it seems to work.

https://github.com/canmet-energy/os_sdk_container/commit/383159a1c0b56a36b5410562e47f625ebbf48820

**Comment by ckirney** [comment]
I believe the issue had to do with differences in the OSs used by NREL vs. Microsoft.  For whatever reason, the date and time generator from Microsoft generated 8760 hours while the one from NREL did not.
